service: aws-node-project

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  websocketsApiName: websockets-api
  websocketsApiRouteSelectionExpression: $request.body.action
  name: aws
  region: "us-east-1"
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  onConnect:
    handler: handler.onConnect
    events:
      - websocket:
          route: $connect
  onDisconnect:
    handler: handler.onDisconnect
    events:
      - websocket:
          route: $disconnect
  onBroadcast:
    handler: handler.onBroadcast
    events:
      - websocket:
          route: broadcast
resources:
  Resources:
    WebSocketTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: web-socket-connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
